#!/bin/bash                                                                     
echo Starting main server.
gnome-terminal -- erl -noshell -name main_server@127.0.0.1 -pa server -config server/config/main -setcookie redgage2020 -s chat_server